;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Montage.Attack.Weapon",NewTagName="CombatSocket.Weapon")
+GameplayTagRedirects=(OldTagName="Montage.Attack.RightHand",NewTagName="CombatSocket.RightHand")
+GameplayTagRedirects=(OldTagName="Montage.Attack.LeftHand",NewTagName="CombatSocket.LeftHand")
+GameplayTagList=(Tag="Attributes",DevComment="Amount of damage a player can take before death")
+GameplayTagList=(Tag="Attributes.Vital.Health",DevComment="")
+GameplayTagList=(Tag="Attributes.Vital.Mana",DevComment="")
+GameplayTagList=(Tag="Event.Montage.FireBolt",DevComment="")
+GameplayTagList=(Tag="GameplayCue.MeleeImpact",DevComment="")
+GameplayTagList=(Tag="Message.HealthCrystal",DevComment="")
+GameplayTagList=(Tag="Message.HealthPotion",DevComment="")
+GameplayTagList=(Tag="Message.ManaCrystal",DevComment="")
+GameplayTagList=(Tag="Message.ManaPotion",DevComment="")

