// acp-dist-tools v5 — vendored 2026-08-10 from native/ACPLicense.cpp
// Do not edit here — edit in acp-dist-tools and re-run sync_dist_tools.sh.
// Product: BPAutoLayout   Lane: native

// ACPLicense.cpp — ACPL2 license checker template (native/C++ lane) implementation.
//
// acp-dist-tools vN — do not edit here, edit in acp-dist-tools and re-sync.
//
// See ACPLicense.h for the full design rationale (two-secret system, why a
// vendored SHA-256 instead of UE's FSHA256, compile-time dev/packaged gate)
// and the BUILD-VERIFICATION STATUS notice — this file was written against
// UE's known public API surface but has NOT been compiled against a real UE
// project. Verify the SHA-256/HMAC output against a known test vector before
// trusting this in a shipped plugin.
//
// Alex Coulombe Presents.
#include "ACPLicense.h"

#include "HAL/FileManager.h"
#include "HAL/PlatformProcess.h"
#include "Misc/Paths.h"
#include "Misc/FileHelper.h"
#include "Interfaces/IPluginManager.h"

// ACPBuildInfo.h is generated by build/build_release.sh.template's native
// lane immediately before compiling, and defines:
//   #define ACP_BUILD_DATE   "YYYY-MM-DD"
//   #define ACP_BUILD_VERSION "x.y.z"
// It only needs to exist for enforcement (Shipping/packaged) builds — a dev
// build never reaches the code path that includes it, since Check() returns
// early below when ACP_LICENSE_ENFORCE is undefined. __has_include guards
// against a dev machine trying to compile with ACP_LICENSE_ENFORCE defined
// by hand but without ever having run the build script (falls through to
// "unknown build date", which fails the com-tier check closed — see below).
#if defined(ACP_LICENSE_ENFORCE) && __has_include("ACPBuildInfo.h")
#include "ACPBuildInfo.h"
#define ACP_HAVE_BUILD_INFO 1
#else
#define ACP_HAVE_BUILD_INFO 0
#endif

namespace ACPLicense
{
	// ========================================================================
	// Vendored SHA-256 (FIPS 180-4). Self-contained, no UE crypto dependency
	// — see ACPLicense.h "WHY A VENDORED SHA-256" for why. Standard
	// unoptimized reference-form implementation: 64-round compression over
	// 512-bit blocks, standard K constants and initial hash values. Operates
	// on TArray<uint8> throughout rather than raw pointers to avoid any
	// buffer-length foot-gun in a security-relevant routine.
	// ========================================================================
	namespace Sha256Internal
	{
		static constexpr uint32 K[64] = {
			0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
			0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
			0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
			0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
			0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
			0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
			0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
			0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
		};

		FORCEINLINE uint32 RotR(uint32 X, uint32 N) { return (X >> N) | (X << (32 - N)); }

		/** Computes the raw 32-byte SHA-256 digest of Data into OutDigest
		 * (must be pre-sized to 32 bytes). */
		void Digest(const TArray<uint8>& Data, TArray<uint8>& OutDigest)
		{
			uint32 H[8] = {
				0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
				0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
			};

			// --- padding: 0x80, zeros, 64-bit big-endian bit length, total a multiple of 64 bytes ---
			const uint64 BitLen = static_cast<uint64>(Data.Num()) * 8ull;
			TArray<uint8> Msg = Data;
			Msg.Add(0x80);
			while ((Msg.Num() % 64) != 56)
			{
				Msg.Add(0x00);
			}
			for (int32 i = 7; i >= 0; --i)
			{
				Msg.Add(static_cast<uint8>((BitLen >> (i * 8)) & 0xFF));
			}
			check((Msg.Num() % 64) == 0);

			// --- process each 512-bit (64-byte) block ---
			const int32 NumBlocks = Msg.Num() / 64;
			for (int32 Block = 0; Block < NumBlocks; ++Block)
			{
				const uint8* P = Msg.GetData() + (Block * 64);

				uint32 W[64];
				for (int32 t = 0; t < 16; ++t)
				{
					W[t] = (static_cast<uint32>(P[t * 4 + 0]) << 24) |
						   (static_cast<uint32>(P[t * 4 + 1]) << 16) |
						   (static_cast<uint32>(P[t * 4 + 2]) << 8) |
						   (static_cast<uint32>(P[t * 4 + 3]));
				}
				for (int32 t = 16; t < 64; ++t)
				{
					const uint32 S0 = RotR(W[t - 15], 7) ^ RotR(W[t - 15], 18) ^ (W[t - 15] >> 3);
					const uint32 S1 = RotR(W[t - 2], 17) ^ RotR(W[t - 2], 19) ^ (W[t - 2] >> 10);
					W[t] = W[t - 16] + S0 + W[t - 7] + S1;
				}

				uint32 a = H[0], b = H[1], c = H[2], d = H[3];
				uint32 e = H[4], f = H[5], g = H[6], h = H[7];

				for (int32 t = 0; t < 64; ++t)
				{
					const uint32 S1 = RotR(e, 6) ^ RotR(e, 11) ^ RotR(e, 25);
					const uint32 Ch = (e & f) ^ ((~e) & g);
					const uint32 Temp1 = h + S1 + Ch + K[t] + W[t];
					const uint32 S0 = RotR(a, 2) ^ RotR(a, 13) ^ RotR(a, 22);
					const uint32 Maj = (a & b) ^ (a & c) ^ (b & c);
					const uint32 Temp2 = S0 + Maj;

					h = g; g = f; f = e; e = d + Temp1;
					d = c; c = b; b = a; a = Temp1 + Temp2;
				}

				H[0] += a; H[1] += b; H[2] += c; H[3] += d;
				H[4] += e; H[5] += f; H[6] += g; H[7] += h;
			}

			OutDigest.SetNumUninitialized(32);
			for (int32 i = 0; i < 8; ++i)
			{
				OutDigest[i * 4 + 0] = static_cast<uint8>((H[i] >> 24) & 0xFF);
				OutDigest[i * 4 + 1] = static_cast<uint8>((H[i] >> 16) & 0xFF);
				OutDigest[i * 4 + 2] = static_cast<uint8>((H[i] >> 8) & 0xFF);
				OutDigest[i * 4 + 3] = static_cast<uint8>(H[i] & 0xFF);
			}
		}

		/** HMAC-SHA256 per RFC 2104, block size 64 bytes as required by SHA-256. */
		void Hmac(const uint8* Key, int32 KeyLen, const TArray<uint8>& Message, TArray<uint8>& OutDigest)
		{
			constexpr int32 BlockSize = 64;

			TArray<uint8> KeyBlock;
			KeyBlock.SetNumZeroed(BlockSize);
			if (KeyLen > BlockSize)
			{
				TArray<uint8> KeyArr;
				KeyArr.Append(Key, KeyLen);
				TArray<uint8> HashedKey;
				Digest(KeyArr, HashedKey);
				FMemory::Memcpy(KeyBlock.GetData(), HashedKey.GetData(), HashedKey.Num());
			}
			else
			{
				FMemory::Memcpy(KeyBlock.GetData(), Key, KeyLen);
			}

			TArray<uint8> InnerPad, OuterPad;
			InnerPad.SetNumUninitialized(BlockSize);
			OuterPad.SetNumUninitialized(BlockSize);
			for (int32 i = 0; i < BlockSize; ++i)
			{
				InnerPad[i] = KeyBlock[i] ^ 0x36;
				OuterPad[i] = KeyBlock[i] ^ 0x5c;
			}

			TArray<uint8> InnerInput = InnerPad;
			InnerInput.Append(Message);
			TArray<uint8> InnerDigest;
			Digest(InnerInput, InnerDigest);

			TArray<uint8> OuterInput = OuterPad;
			OuterInput.Append(InnerDigest);
			Digest(OuterInput, OutDigest);
		}

		FString ToHexLower(const TArray<uint8>& Bytes)
		{
			static const TCHAR* HexChars = TEXT("0123456789abcdef");
			FString Out;
			Out.Reserve(Bytes.Num() * 2);
			for (uint8 B : Bytes)
			{
				Out.AppendChar(HexChars[(B >> 4) & 0xF]);
				Out.AppendChar(HexChars[B & 0xF]);
			}
			return Out;
		}
	} // namespace Sha256Internal

	FString ComputeSignature(
		const FString& Product, const FString& Licensee, const FString& Email,
		const FString& Tier, int32 Seats, const FString& Expiry,
		const uint8* Secret, int32 SecretLen)
	{
		// Must match python/acp_license.py::compute_signature()'s payload
		// EXACTLY (same field order, same '|' delimiter, same UTF-8 bytes) or
		// a license signed by the Python keygen will never verify here.
		const FString Payload = FString::Printf(
			TEXT("ACPL2|%s|%s|%s|%s|%d|%s"), *Product, *Licensee, *Email, *Tier, Seats, *Expiry);

		FTCHARToUTF8 Utf8Payload(*Payload);
		TArray<uint8> PayloadBytes;
		PayloadBytes.Append(reinterpret_cast<const uint8*>(Utf8Payload.Get()), Utf8Payload.Length());

		TArray<uint8> DigestBytes;
		Sha256Internal::Hmac(Secret, SecretLen, PayloadBytes, DigestBytes);
		return Sha256Internal::ToHexLower(DigestBytes);
	}

	bool ParseLicense(const FString& RawText, FLicenseInfo& OutInfo)
	{
		FString Trimmed = RawText.TrimStartAndEnd();

		TArray<FString> Parts;
		// ParseIntoArray with a false "cull empty" arg would collapse an
		// empty field (e.g. an empty licensee) into a missing entry and
		// silently shift every field after it — pass false explicitly so a
		// malformed license with an empty field is caught by the count
		// check below instead of misparsing.
		Trimmed.ParseIntoArray(Parts, TEXT("|"), /*InCullEmpty=*/false);

		if (Parts.Num() != 8 || Parts[0] != TEXT("ACPL2"))
		{
			return false;
		}

		const FString& Tier = Parts[4];
		if (Tier != TEXT("edu") && Tier != TEXT("com"))
		{
			return false;
		}

		if (!Parts[5].IsNumeric())
		{
			return false;
		}
		const int32 Seats = FCString::Atoi(*Parts[5]);
		if (Seats < 1)
		{
			return false;
		}

		FDateTime ParsedExpiry;
		if (!FDateTime::ParseIso8601(*(Parts[6] + TEXT("T00:00:00")), ParsedExpiry))
		{
			return false;
		}

		OutInfo.Product = Parts[1];
		OutInfo.Licensee = Parts[2];
		OutInfo.Email = Parts[3];
		OutInfo.Tier = Tier;
		OutInfo.Seats = Seats;
		OutInfo.Expiry = Parts[6];
		OutInfo.Signature = Parts[7].ToLower();
		return true;
	}

	static bool ConstantTimeEquals(const FString& A, const FString& B)
	{
		// Constant-time over the LONGER of the two lengths so even a
		// length mismatch doesn't short-circuit early — deliberately not
		// A.Equals(B), see the header comment on VerifySignature().
		const int32 LenA = A.Len();
		const int32 LenB = B.Len();
		const int32 MaxLen = FMath::Max(LenA, LenB);
		uint32 Diff = static_cast<uint32>(LenA ^ LenB);
		for (int32 i = 0; i < MaxLen; ++i)
		{
			const TCHAR CA = (i < LenA) ? A[i] : 0;
			const TCHAR CB = (i < LenB) ? B[i] : 0;
			Diff |= static_cast<uint32>(CA ^ CB);
		}
		return Diff == 0;
	}

	bool VerifySignature(const FLicenseInfo& Info, const uint8* Secret, int32 SecretLen)
	{
		const FString Expected = ComputeSignature(
			Info.Product, Info.Licensee, Info.Email, Info.Tier, Info.Seats, Info.Expiry, Secret, SecretLen);
		return ConstantTimeEquals(Expected, Info.Signature);
	}

	static FString LicenseFilePath()
	{
		// Locate the plugin by its actual UE descriptor name
		// (PluginDirectoryName — the .uplugin file's basename, which is what
		// IPluginManager indexes plugins by; see the header comment on
		// PluginDirectoryName for why this must NOT be ProductId) and read
		// <ProductId>.license (the licensing name, which can differ) from
		// its base directory, next to the .uplugin file. Requires the
		// "Projects" module as a dependency (IPluginManager lives there) —
		// add it to the consuming plugin's Build.cs
		// PrivateDependencyModuleNames if not already present.
		TSharedPtr<IPlugin> Plugin = IPluginManager::Get().FindPlugin(PluginDirectoryName);
		if (!Plugin.IsValid())
		{
			// Fallback: some plugins may not self-report via IPluginManager
			// in every build configuration. Fall back to a path relative to
			// this source file's location at compile time is NOT reliable
			// at runtime (source tree != install tree), so instead fall back
			// to empty, which Check() treats as "file not found" — same
			// user-visible behavior (MISSING) as a genuinely absent license.
			return FString();
		}
		return FPaths::Combine(Plugin->GetBaseDir(), FString(ProductId) + TEXT(".license"));
	}

	static FString TrialMarkerPath()
	{
		// UserSettingsDir is Application Support/Epic on macOS, LocalAppData on
		// Windows, and ~/.config/Epic on Linux. Keeping the marker outside the
		// plugin tree prevents an ordinary update/reinstall from resetting it.
		return FPaths::Combine(FPlatformProcess::UserSettingsDir(), TEXT("AlexCoulombePresents"),
			TEXT("ACPL2Trials"), FString(ProductId) + TEXT(".trial"));
	}

	static FLicenseResult MakeTrialResult(const FDateTime& Start, const FDateTime& Now)
	{
		FLicenseResult Result;
		const FDateTime Expiry = Start + FTimespan::FromDays(TrialDays);
		FLicenseInfo Info;
		Info.Tier = TEXT("trial");
		Info.Expiry = Expiry.ToIso8601();
		Result.Info = Info;

		if (Now >= Expiry)
		{
			Result.bOk = false;
			Result.Status = EStatus::TrialExpired;
			Result.Message = FString::Printf(TEXT("Trial expired — see %s"), Contact);
			return Result;
		}

		const int32 DaysRemaining = FMath::Max(1, FMath::CeilToInt((Expiry - Now).GetTotalDays()));
		Result.bOk = true;
		Result.Status = EStatus::Trial;
		Result.Message = FString::Printf(TEXT("Trial active — %d day(s) remaining"), DaysRemaining);
		return Result;
	}

	static FLicenseResult CheckOrStartTrial()
	{
		const FString Path = TrialMarkerPath();
		const FDateTime Now = FDateTime::UtcNow();
		FString RawStart;
		if (!FPaths::FileExists(Path))
		{
			if (!IFileManager::Get().MakeDirectory(*FPaths::GetPath(Path), /*Tree=*/true) ||
				!FFileHelper::SaveStringToFile(Now.ToIso8601(), *Path,
					FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM))
			{
				FLicenseResult Result;
				Result.bOk = false;
				Result.Status = EStatus::TrialUnavailable;
				Result.Message = FString::Printf(TEXT("Trial could not be started — see %s"), Contact);
				return Result;
			}
			return MakeTrialResult(Now, Now);
		}

		FDateTime Start;
		if (!FFileHelper::LoadFileToString(RawStart, *Path) ||
			!FDateTime::ParseIso8601(*RawStart.TrimStartAndEnd(), Start))
		{
			// Do not replace a corrupt marker: that would let a user reset the
			// timer by editing it. This remains deterrence-tier, not hard DRM.
			FLicenseResult Result;
			Result.bOk = false;
			Result.Status = EStatus::TrialExpired;
			Result.Message = FString::Printf(TEXT("Trial expired — see %s"), Contact);
			return Result;
		}
		return MakeTrialResult(Start, Now);
	}

	FLicenseResult Check()
	{
#if !defined(ACP_LICENSE_ENFORCE)
		// Dev/Editor build: enforcement compiled out entirely. See header
		// comment on ACP_LICENSE_ENFORCE — this mirrors the Python lane's
		// promise that a dev checkout never needs a license file.
		FLicenseResult Result;
		Result.bOk = true;
		Result.Status = EStatus::DevMode;
		Result.Message = TEXT("dev build — license check compiled out (ACP_LICENSE_ENFORCE not defined)");
		return Result;
#else
		const FString RequiredMsg = FString::Printf(TEXT("License required — see %s"), Contact);
		const FString InvalidMsg = FString::Printf(TEXT("License invalid — see %s"), Contact);
		const FString WrongProductMsg = FString::Printf(TEXT("License is for a different product — see %s"), Contact);
		const FString ExpiredMsg = FString::Printf(TEXT("License expired — see %s"), Contact);

		FLicenseResult Result;

		const FString Path = LicenseFilePath();
		if (Path.IsEmpty())
		{
			// A plugin lookup failure is a configuration problem, not evidence
			// that this user has never received a license. Preserve the ordinary
			// Missing result rather than accidentally granting a fresh trial.
			Result.bOk = false;
			Result.Status = EStatus::Missing;
			Result.Message = RequiredMsg;
			return Result;
		}
		if (!FPaths::FileExists(Path))
		{
			// A signed license wins whenever it exists. Only a genuinely absent
			// file may start/resume the local self-service trial.
			return CheckOrStartTrial();
		}

		FString RawText;
		if (!FFileHelper::LoadFileToString(RawText, *Path))
		{
			Result.bOk = false;
			Result.Status = EStatus::Missing;
			Result.Message = RequiredMsg;
			return Result;
		}

		FLicenseInfo Info;
		if (!ParseLicense(RawText, Info))
		{
			// Any parse/format surprise (truncated file, bad date, old
			// format, garbage) is indistinguishable from "not licensed" to
			// the user — never a crash/ensure/check() failure.
			Result.bOk = false;
			Result.Status = EStatus::Malformed;
			Result.Message = InvalidMsg;
			return Result;
		}
		Result.Info = Info;

		if (!VerifySignature(Info, SecretNative, UE_ARRAY_COUNT(SecretNative)))
		{
			Result.bOk = false;
			Result.Status = EStatus::InvalidSignature;
			Result.Message = InvalidMsg;
			return Result;
		}

		if (Info.Product != FString(ProductId))
		{
			Result.bOk = false;
			Result.Status = EStatus::WrongProduct;
			Result.Message = WrongProductMsg;
			return Result;
		}

		if (Info.Tier == TEXT("edu"))
		{
			// Hard expiry: compared against TODAY.
			const FDateTime Today = FDateTime::Now();
			FDateTime Expiry;
			FDateTime::ParseIso8601(*(Info.Expiry + TEXT("T00:00:00")), Expiry);
			if (Today.GetDate() > Expiry.GetDate())
			{
				Result.bOk = false;
				Result.Status = EStatus::Expired;
				Result.Message = ExpiredMsg;
				return Result;
			}
		}
		else // "com"
		{
			// Update-window end, NOT a kill switch: compared against THIS
			// BUILD's stamped ACP_BUILD_DATE, never today's date. A lapsed
			// commercial customer keeps using what they paid for forever —
			// they just can't run a build newer than their paid-through date.
#if ACP_HAVE_BUILD_INFO
			FDateTime BuildDate;
			const bool bHaveDate = FDateTime::ParseIso8601(TEXT(ACP_BUILD_DATE) TEXT("T00:00:00"), BuildDate);
#else
			const bool bHaveDate = false;
			FDateTime BuildDate;
#endif
			if (!bHaveDate)
			{
				// Unknown build date fails CLOSED (unlike dev-mode above)
				// specifically so stripping ACPBuildInfo.h from a packaged
				// build can't be used to bypass the com-tier window.
				Result.bOk = false;
				Result.Status = EStatus::Expired;
				Result.Message = ExpiredMsg;
				return Result;
			}
			FDateTime Expiry;
			FDateTime::ParseIso8601(*(Info.Expiry + TEXT("T00:00:00")), Expiry);
			if (BuildDate.GetDate() > Expiry.GetDate())
			{
				Result.bOk = false;
				Result.Status = EStatus::Expired;
				Result.Message = ExpiredMsg;
				return Result;
			}
		}

		Result.bOk = true;
		Result.Status = EStatus::Ok;
		Result.Message = FString::Printf(TEXT("licensed to %s (%s, expires %s)"), *Info.Licensee, *Info.Tier, *Info.Expiry);
		return Result;
#endif // ACP_LICENSE_ENFORCE
	}

	bool CheckEntitlement(const FString& LicenseText, bool& bOutHasData)
	{
		// STUB — see header. Never call out to a network here until the
		// entitlement API actually exists; a real implementation must treat
		// network failure as "no data", never "not entitled".
		(void)LicenseText;
		bOutHasData = false;
		return false;
	}

} // namespace ACPLicense
